### ISSUE TITLE
Dont build agent

### ISSUE THREAD

**Issue by unknow-agent** [yvasiyarov/newrelic_sphinx#12]
$ go get github.com/yunge/sphinx
 $ go get github.com/yvasiyarov/newrelic_platform_go
 $ git clone https://github.com/yvasiyarov/newrelic_sphinx.git   
 $ cd newrelic_sphinx   
 $ go build -o sphinx_agent
 # gosphinx/newrelic_sphinx
 ./sphinx_agent.go:57: not enough arguments in call to newrelic_platform_go.NewPluginComponent

and don't build agent. How to fix this?

**Comment by maximelamure** [comment]
sphinx_agent.go , line 58, just add the verbose option : *verbose
```
component := newrelic_platform_go.NewPluginComponent(*newrelicName, AGENT_GUID, *verbose)
```
Unfortunately, I don't have the rights to push a PR.
