### ISSUE TITLE
Can not get metrica: commands/Command flushattrs

### ISSUE THREAD

**Issue by massdest** [yvasiyarov/newrelic_sphinx#8]
Hello, Plugin show error on startup:
2014/07/03 18:18:21 Can not get metrica: commands/Command flushattrs, got error:&errors.errorString{s:"Can not get data from source \n"}
2014/07/03 18:19:21 Can not get metrica: commands/Command flushattrs, got error:&errors.errorString{s:"Can not get data from source \n"}

ubuntu 12.04
go version go1.1.1 linux/amd64
Sphinx 0.9.9-release (r2117)

**Comment by dipankar** [comment]
@massdest just to update, Sphinx has a few ways of accessing the data. It looks like this plugin works only with the native Sphinx inteface. Hope that helps!

**Comment by massdest** [comment]
I forget about this issue, in my case this plug-in work's on most recent sphinx version - 2.1.9-id64-release.
